# Generated by Django 3.2.3 on 2021-07-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('desc', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'ContactInfo',
            },
        ),
    ]
